version: "3.6"
services:
  stream:
    build: ./stream
    image: satbox:stream
    restart: always
    volumes:
      - /var/log/satbox/stream:/usr/src/app/logs
  queue:
    build: ./queue
    image: satbox:queue
    restart: always
    ports:
      - "5000:5000"
